language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible

script:
  - "python setup.py test"

after_script:
  - config/deploy

notifications:
  irc: "irc.freenode.org#takeyourmeds"
