sudo: required
python: "2.7"
language: python

services:
  - docker

install:
  - pip install -r requirements.txt coveralls

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

deploy:
  script: config/deploy
  provider: script
  skip_cleanup: true

after_success:
  - coveralls
