---
- name: setup
  hosts: all
  roles:
    - apt
    - hostname
    - locale
    - timezone
    - mailx
    - molly-guard
    - firewall

    - postgresql
    - redis

- name: deploy
  hosts: all
  roles:
    - takeyourmeds
