---
# TODO: backups

- name: all
  hosts: all
  gather_facts: false
  sudo: true

- name: all
  hosts: all
  roles:
    - apt
    - hostname
    - locale
    - timezone
    - mailx
    - molly-guard
    - firewall

    - postgresql
    - redis

- name: install build-dependencies for package
  raw:
    DEBIAN_FRONTEND=noninteractive mk-build-deps --install --remove --tool 'apt-get --no-install-recommends --yes' .

- name: build .debs
  raw:
    dpkg-buildpackage -uc -us -b

- name: stop nginx
  service:
    name=nginx
    state=stopped

- name: stop queues gracefully (remove package??)
  service:
    name=takeyourmeds-celery
    state=stopped

- name: install debs
  action: raw
    cmd=dpkg -i {{ item }}*.deb
  with_items:
    - takeyourmeds-web
    - takeyourmeds-celery

- name: ensure basic postgres config
  action: raw
    cmd=sudo -u postgres {{ item }} || true
  with_items:
    - createuser takeyourmeds -SDR
    - createdb -E UTF-8 -O takeyourmeds takeyourmeds

- name: run migrations
  raw:
    sudo -u www-data {{ base_dir }}/bin/manage.py migrate --verbosity=2

- name: start queues
  service:
    name=takeyourmeds-celery
    state=started

- name: start nginx
  service:
    name=nginx
    state=started
