---
- name: all
  hosts: all
  gather_facts: false
  sudo: true

- name: all
  hosts: all
  roles:
    - apt
    - hostname
    - locale
    - timezone
    - mailx
    - molly-guard
    - firewall

    - postgresql
    - redis
