---
- name: Install packages required to build Debian packages in general
  action: apt
    pkg={{ item }}
  with_items:
    - equivs
    - devscripts
    - build-essential

- name: Remove any existing build directory
  changed_when: False
  file:
    state=absent
    path={{ build_dir }}

- name: Create build directory
  changed_when: False
  file:
    state=directory
    path={{ build_dir }}/src

- name: Download code
  changed_when: False
  command:
    wget -O {{ build_dir }}/src.tar.gz {{ source }}/archive/{{ branch }}.tar.gz

- name: Extract
  changed_when: False
  command:
    tar xfz {{ build_dir }}/src.tar.gz --strip-components=1 --directory={{ build_dir }}/src

- name: Install the specific packages required to build our Debian packages
  changed_when: False
  command:
    mk-build-deps --install --remove --tool "apt-get --no-install-recommends --target-release={{ debian_release }}-backports --yes" debian/control
  args:
    chdir: "{{ build_dir }}/src"

- name: Build packages
  changed_when: False
  command:
    dpkg-buildpackage -uc -us -b
  args:
    chdir: "{{ build_dir }}/src"

- name: Install packages
  action: shell
    dpkg -i {{ build_dir }}/{{ item }}*.deb
  with_items:
    - takeyourmeds-web
    - takeyourmeds-celery
