---
- name: Copy package
  copy:
    src=takeyourmeds.deb
    dest=/tmp/takeyourmeds.deb

- name: Stop services to avoid race conditions
  action: service
    name={{ item }}
    state=stopped
  with_items:
    - nginx
    - takeyourmeds-celery
    - takeyourmeds-gunicorn
  ignore_errors: yes # Permit initial installation

- name: Create storage directory
  file:
    state=directory
    path={{ storage_dir }}
    mode=0755
    owner=www-data

- name: Install package
  shell:
    dpkg -i /tmp/takeyourmeds.deb
  ignore_errors: yes # For new dependencies

- name: Ensure dependencies
  shell:
    apt-get -f --yes install

- name: Set role
  template:
    src=role.py
    dest={{ site_packages }}/takeyourmeds/role.py
  no_log: true

- name: Set custom/secret settings
  template:
    src=custom.py
    dest={{ site_packages }}/takeyourmeds/settings/custom.py
  no_log: true

- name: Setup PostgreSQL user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name=takeyourmeds
    password=takeyourmeds

- name: Setup PostgreSQL database
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name=takeyourmeds
    owner=takeyourmeds
    encoding=UTF-8

- name: Run migrations
  sudo: yes
  sudo_user: www-data
  shell:
    "{{ base_dir }}/bin/manage.py migrate --verbosity=2 --noinput --fake-initial 2>&1"
  register: out
- debug: var=out.stdout_lines

- name: collectstatic
  command:
    "{{ base_dir }}/bin/manage.py collectstatic --verbosity=2 --noinput --clear --link"

- name: Start services again
  action: service
    name={{ item }}
    state=started
  with_items:
    - takeyourmeds-gunicorn
    - takeyourmeds-celery
    - nginx
