---
- name: Install packages required to build Debian packages in general
  action: apt
    pkg={{ item }}
  with_items:
    - equivs
    - devscripts
    - build-essential

- name: Remove any existing build directory
  file:
    state=absent
    path={{ build_dir }}

- name: Create build directory
  file:
    state=directory
    path={{ build_dir }}/src

- name: Download code
  command:
    wget -O {{ build_dir }}/src.tar.gz {{ source }}/archive/{{ branch }}.tar.gz

- name: Extract
  command:
    tar xfz {{ build_dir }}/src.tar.gz --strip-components=1 --directory={{ build_dir }}/src

- name: Set role
  template:
    src=role.py
    dest={{ build_dir }}/src/takeyourmeds/settings/role.py

- name: Install the specific packages required to build our Debian packages
  command:
    mk-build-deps --install --remove --tool "apt-get --no-install-recommends --target-release={{ debian_release }}-backports --yes" debian/control
  args:
    chdir: "{{ build_dir }}/src"

- name: Build packages
  command:
    dpkg-buildpackage -uc -us -b
  args:
    chdir: "{{ build_dir }}/src"

- name: Stop services to avoid race conditions
  action: service
    name={{ item }}
    state=stopped
  with_items:
    - nginx
    - takeyourmeds-celery
    - takeyourmeds-gunicorn

- name: Install packages
  action: shell
    dpkg -i {{ build_dir }}/{{ item }}_*.deb
  with_items:
    - takeyourmeds-web
    - takeyourmeds-celery
    - takeyourmeds-gunicorn

- name: Start services again
  action: service
    name={{ item }}
    state=started
  with_items:
    - takeyourmeds-gunicorn
    - takeyourmeds-celery
    - nginx
